# Generated by Django 5.0.1 on 2024-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="recipient",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.EmailField(max_length=254),
        ),
    ]
